package org.mydrugs.mydrugs.datagen;

import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;
import org.mydrugs.mydrugs.MyDrugs;
import org.mydrugs.mydrugs.blocks.ModBlocks;
import org.mydrugs.mydrugs.blocks.crops.ModCrops;
import org.mydrugs.mydrugs.fluids.FluidEntry;
import org.mydrugs.mydrugs.fluids.ModFluids;
import org.mydrugs.mydrugs.items.ModItems;

public class ModLangProvider extends LanguageProvider {
    public ModLangProvider(PackOutput output) {
        super(output, MyDrugs.MODID, "en_us");
    }

    private static String pretty(String name) {
        String[] parts = name.split("_");
        StringBuilder builder = new StringBuilder();

        for (int i = 0; i < parts.length; i++) {
            if (i > 0) builder.append(' ');
            builder.append(Character.toUpperCase(parts[i].charAt(0)));
            builder.append(parts[i].substring(1));
        }

        return builder.toString();
    }

    @Override
    protected void addTranslations() {
        ModItems.SPACE_FOODS_BY_BASE_ID.forEach((baseId, item)
                -> this.addItem(item, "Space " + pretty(baseId.getPath())));

        // Blocks
        add(ModBlocks.ADVANCED_FURNACE.get(), "Advanced Furnace");
        add(ModBlocks.MIXING_VAT.get(), "Mixing Vat");
        add(ModBlocks.ELECTROLYZER.get(), "Electrolyzer");
        add(ModBlocks.AROMATIC_EXTRACTOR.get(), "Aromatic Extractor");
        add(ModBlocks.BTX_FRACTIONATION_TOWER.get(), "BTX Fractionation Tower");
        add(ModBlocks.BASIC_ITEM_PIPE.get(), "Basic Item Pipe");
        add(ModBlocks.FAST_ITEM_PIPE.get(), "Fast Item Pipe");
        add(ModBlocks.BASIC_FLUID_PIPE.get(), "Basic Fluid Pipe");
        add(ModBlocks.FAST_FLUID_PIPE.get(), "Fast Fluid Pipe");
        add(ModBlocks.BASIC_GAS_PIPE.get(), "Basic Gas Pipe");
        add(ModBlocks.FAST_GAS_PIPE.get(), "Fast Gas Pipe");
        add(ModBlocks.FLUID_PUMP.get(), "Fluid Pump");
        add(ModBlocks.PLATINUM_ORE.get(), "Platinum Ore");
        add(ModBlocks.DEEPSLATE_PLATINUM_ORE.get(), "Deepslate Platinum Ore");
        add(ModBlocks.RAW_PLATINUM_BLOCK.get(), "Block of Raw Platinum");
        add(ModBlocks.PLATINUM_BLOCK.get(), "Block of Platinum");
        add(ModBlocks.ALUMINIUM_ORE.get(), "Aluminium Ore");
        add(ModBlocks.DEEPSLATE_ALUMINIUM_ORE.get(), "Deepslate Aluminium Ore");
        add(ModBlocks.RAW_ALUMINIUM_BLOCK.get(), "Block of Raw Aluminium");
        add(ModBlocks.ALUMINIUM_BLOCK.get(), "Block of Aluminium");
        add(ModBlocks.MECHANICAL_FRAME.get(), "Mechanical Frame");
        add(ModBlocks.PSY_ANVIL.get(), "Psy Anvil");
        add(ModBlocks.RECOVERY_ANCHOR.get(), "Recovery Anchor");
        add(ModBlocks.THERAPIST_DESK.get(), "Therapist Desk");
        add(ModBlocks.DISC_SCRIBER.get(), "Disc Scriber");
        add(ModBlocks.RECOVERY_JUKEBOX.get(), "Recovery Jukebox");
        add(ModBlocks.GENE_EXTRACTOR.get(), "Gene Extractor");
        add(ModBlocks.CRISPR_CAS9_COMBINATOR.get(), "CRISPR-CAS9 Combinator");
        add("block.mydrugs.krispr_kas9_combinator", "CRISPR-CAS9 Combinator");
        add(ModBlocks.BACTERIAL_INCUBATOR.get(), "Bacterial Incubator");
        add(ModBlocks.HEMOGENIC_INFUSER.get(), "Hemogenic Infuser");
        add(ModBlocks.AUTOCLAVE.get(), "Autoclave");
        add(ModBlocks.PSYCHOTROPE_DISTILLERY.get(), "Psychotrope Distillery");
        add(ModBlocks.DISTILLATE_ENGINE.get(), "Distillate Engine");
        add(ModBlocks.PSYCHOTROPE_RESONATOR.get(), "Psychotrope Resonator");
        add(ModBlocks.ALOE_VERA_BUSH.get(), "Aloe Vera Bush");
        add(ModCrops.ALOE_VERA_CROP.get(), "Aloe Vera Crop");
        add(ModCrops.LAVENDER_CROP.get(), "Lavender Crop");
        add(ModCrops.VALERIAN_CROP.get(), "Valerian Crop");
        add(ModCrops.OPIUM_POPPY_CROP.get(), "Poppy Crop");
        add(ModCrops.EPHEDRA_CROP.get(), "Ephedra Shrub");
        add(ModCrops.EPHEDRA_CUTTINGS.get(), "Ephedra Cuttings");
        add(ModBlocks.REDUCTION_STILL.get(), "Reduction Still");
        add("container.mydrugs.reduction_still", "Reduction Still");
        add("menu.mydrugs.reduction_still", "Reduction Still");
        add("screen.mydrugs.reduction_still.status.working", "Working: %s / %s ticks");
        add("screen.mydrugs.reduction_still.status.missing_cuttings", "Missing: ephedra cuttings");
        add("screen.mydrugs.reduction_still.status.missing_solvent", "Missing: water bucket (solvent)");
        add("screen.mydrugs.reduction_still.status.need_more_cuttings", "Need more cuttings for next batch");
        add("screen.mydrugs.reduction_still.status.output_blocked", "Output blocked: clear extract or spent pulp");
        add(ModBlocks.PHOSPHATE_ORE.get(), "Phosphate Ore");
        add(ModBlocks.DEEPSLATE_PHOSPHATE_ORE.get(), "Deepslate Phosphate Ore");
        add(ModItems.RAW_PHOSPHORUS.get(), "Raw Phosphorus");
        add(ModItems.REACTIVE_PHOSPHORUS.get(), "Reactive Phosphorus");
        add(ModItems.EPHEDRA_EXTRACT.get(), "Concentrated Ephedra Extract");
        add(ModItems.SPENT_PLANT_PULP.get(), "Spent Plant Pulp");
        add(ModItems.CRUDE_REACTANT_CAKE.get(), "Crude Reactant Cake");
        add("container.mydrugs.autoclave", "Autoclave");
        add("menu.mydrugs.autoclave", "Autoclave");
        add("screen.mydrugs.autoclave.progress", "Sterilization Progress");
        add("screen.mydrugs.autoclave.progress_amount", "%s / %s ticks, %s PE/t");
        add("machine_transfer_port.mydrugs.syringe_input", "Syringe Input");
        add("machine_transfer_port.mydrugs.syringe_output", "Syringe Output");
        add("container.mydrugs.btx_fractionation_tower", "BTX Fractionation Tower");
        add("container.mydrugs.gene_extractor", "Gene Extractor");
        add("menu.mydrugs.gene_extractor", "Gene Extractor");
        add("container.mydrugs.crispr_cas9_combinator", "CRISPR-CAS9 Combinator");
        add("menu.mydrugs.crispr_cas9_combinator", "CRISPR-CAS9 Combinator");
        add("container.mydrugs.bacterial_incubator", "Bacterial Incubator");
        add("menu.mydrugs.bacterial_incubator", "Bacterial Incubator");
        add("container.mydrugs.hemogenic_infuser", "Hemogenic Infuser");
        add("menu.mydrugs.hemogenic_infuser", "Hemogenic Infuser");
        add("container.mydrugs.psychotrope_distillery", "Psychotrope Distillery");
        add("menu.mydrugs.psychotrope_distillery", "Psychotrope Distillery");
        add("container.mydrugs.distillate_engine", "Distillate Engine");
        add("menu.mydrugs.distillate_engine", "Distillate Engine");
        add("container.mydrugs.psychotrope_resonator", "Psychotrope Resonator");
        add("menu.mydrugs.psychotrope_resonator", "Psychotrope Resonator");

        // Items
        add(ModItems.GLASS_BOTTLE.get(), "Glass Bottle");
        add(ModItems.PROGRESSION_GUIDE.get(), "MyDrugs Field Guide");
        add(ModItems.ADN_SCRAPER.get(), "ADN Scraper");
        add(ModItems.ADN_SCRAP.get(), "ADN Scrap");
        add(ModItems.ADN_GENE.get(), "ADN Gene");
        add(ModItems.MUTATION_VECTOR.get(), "Mutation Vector");
        add(ModItems.MUTAGENIC_BLOOD_VIAL.get(), "Mutagenic Blood Vial");
        add(ModItems.NUTRIENT_GEL.get(), "Nutrient Gel");
        add(ModItems.PIPE_WRENCH.get(), "Pipe Wrench");
        add(ModItems.PIPE_FILTER_UPGRADE.get(), "Pipe Filter Upgrade");
        add(ModItems.MACHINE_TRANSFER_UPGRADE.get(), "Machine Transfer Upgrade");
        add(ModItems.LUCID_EXTRACT.get(), "Lucid Extract");
        add(ModItems.CALMING_RESIN.get(), "Calming Resin");
        add(ModItems.REDLINE_FUEL.get(), "Redline Fuel");
        add(ModItems.OVERDRIVE_FUEL.get(), "Overdrive Fuel");
        add(ModItems.UNSTABLE_ESSENCE.get(), "Unstable Essence");
        add(ModItems.DREAM_RESIDUE.get(), "Dream Residue");
        add(ModItems.MYCELIAL_INSIGHT.get(), "Mycelial Insight");
        add(ModItems.PRESSED_CALM.get(), "Pressed Calm");
        add(ModItems.FERMENTED_MEMORY.get(), "Fermented Memory");
        add(ModItems.BITTER_RESIDUE.get(), "Bitter Residue");
        add(ModItems.BURNT_NERVE_RESIDUE.get(), "Burnt Nerve Residue");
        add(ModItems.SPENT_FILTER.get(), "Spent Filter");
        add(ModItems.DISTILLATION_COIL.get(), "Distillation Coil");
        add(ModItems.CURRENT_REGULATOR.get(), "Current Regulator");
        add(ModItems.STRAIN_VENT.get(), "Strain Vent");
        add(ModItems.RESONANCE_LENS.get(), "Resonance Lens");
        add(ModItems.INTEGRATION_CORE.get(), "Integration Core");
        add(ModItems.ENERGY_UPGRADE.get(), "Energy Upgrade");
        add(ModItems.AUTOMATION_UPGRADE.get(), "Automation Upgrade");
        add(ModItems.CIGARET_FILTER.get(), "Cigarette Filter");
        add(ModItems.PSY_RECEPTACLE.get(), "Psy Receptacle");
        add(ModItems.HEAVY_IRON_PLATE.get(), "Heavy Iron Plate");
        add(ModItems.INNER_DEMON_REMAINS.get(), "Inner Demon Remains");
        add(ModItems.MYCELIAL_RESONATOR.get(), "Mycelial Resonator");
        add(ModItems.INSULATED_WIRE.get(), "Insulated Wire");
        add(ModItems.CONTROL_CIRCUIT.get(), "Control Circuit");
        add(ModItems.ADVANCED_CONTROL_CIRCUIT.get(), "Advanced Control Circuit");
        add(ModItems.ALOE_VERA.get(), "Aloe Vera Leaf");
        add(ModItems.LAVENDER.get(), "Lavender");
        add(ModItems.DRIED_LAVENDER.get(), "Dried Lavender");
        add(ModItems.VALERIAN_ROOT.get(), "Valerian Root");
        add(ModItems.BLANK_MUSIC_DISC.get(), "Blank Music Disc");
        add(ModItems.PERSONAL_MUSIC_DISC.get(), "Personal Music Disc");
        add(ModItems.CAFFEINE_BAR.get(), "Caffeine Bar");
        add(ModItems.MARRAKECH_BUTTER.get(), "Marrakech Butter");
        add("entity.mydrugs.stoned_cow", "Stoned Cow");
        add("entity.mydrugs.stoned_mooshroom", "Stoned Mooshroom");
        add(ModCrops.ALOE_VERA_SEEDS.get(), "Aloe Vera Seeds");
        add(ModCrops.LAVENDER_SEEDS.get(), "Lavender Seeds");
        add(ModCrops.VALERIAN_SEEDS.get(), "Valerian Seeds");
        add(ModCrops.COCA_SEEDS.get(), "Coca Seeds");
        add(ModCrops.OPIUM_POPPY_SEEDS.get(), "Poppy Seeds");
        add(ModItems.ELECTRIC_MOTOR.get(), "Electric Motor");
        add(ModItems.HEATING_COIL.get(), "Heating Coil");
        add(ModItems.CONDENSER_COIL.get(), "Condenser Coil");
        add(ModItems.ELECTRODE_PAIR.get(), "Electrode Pair");
        add(ModItems.CATALYST_BED.get(), "Catalyst Bed");
        add(ModItems.PACKED_COLUMN.get(), "Packed Column");
        add(ModItems.PIPE_JOINT.get(), "Pipe Joint");
        add(ModItems.PSYCHOTROPE_LENS.get(), "Psychotrope Lens");
        add(ModItems.RAW_PLATINUM.get(), "Raw Platinum");
        add(ModItems.PLATINUM_INGOT.get(), "Platinum Ingot");
        add(ModItems.RAW_ALUMINIUM.get(), "Raw Aluminium");
        add(ModItems.ALUMINIUM_INGOT.get(), "Aluminium Ingot");
        add("menu.mydrugs.pipe_filter", "Pipe Filter");
        add("menu.mydrugs.machine_transfer_config", "Machine Transfer Configuration");
        add("message.mydrugs.pipe.side_mode", "%s: %s");
        add("message.mydrugs.pipe_filter.applied", "%s filter applied: %s %s (%s entries)");
        add("tooltip.mydrugs.pipe_filter.kind", "Kind: %s");
        add("tooltip.mydrugs.pipe_filter.mode", "Mode: %s");
        add("tooltip.mydrugs.pipe_filter.entries", "Entries: %s");
        add("screen.mydrugs.pipe_filter.placeholder", "Filter research prototype");
        add("screen.mydrugs.pipe_filter.instructions", "Prototype filters store their configured data on the upgrade item.");
        add("message.mydrugs.transfer_upgrade.installed", "Transfer upgrade installed");
        add("message.mydrugs.transfer_upgrade.already_installed", "Transfer upgrade already installed");
        add("message.mydrugs.energy_upgrade.installed", "Energy Upgrade installed.");
        add("message.mydrugs.energy_upgrade.already_installed", "Energy Upgrade already installed.");
        add("message.mydrugs.energy_upgrade.has_automation", "This machine already has an Automation Upgrade.");
        add("message.mydrugs.energy_upgrade.unsupported", "This machine does not support this upgrade.");
        add("message.mydrugs.automation_upgrade.installed", "Automation Upgrade installed.");
        add("message.mydrugs.automation_upgrade.already_installed", "Automation Upgrade already installed.");
        add("message.mydrugs.automation_upgrade.has_energy", "This machine already has an Energy Upgrade.");
        add("message.mydrugs.automation_upgrade.unsupported", "This machine does not support this upgrade.");
        add("tooltip.mydrugs.machine_upgrade.transfer", "Machine Transfer Upgrade installed");
        add("tooltip.mydrugs.machine_upgrade.energy", "Energy Upgrade installed");
        add("tooltip.mydrugs.machine_upgrade.automation", "Automation Upgrade installed");
        add("screen.mydrugs.machine_transfer.target", "Target: %s");
        add("screen.mydrugs.machine_transfer.ports", "Ports detected: %s");
        add("screen.mydrugs.machine_transfer.instructions", "Port and side rules will be synced here as machines migrate.");
        add("screen.mydrugs.machine_transfer.title", "Transfer Configuration");
        add("screen.mydrugs.machine_transfer.port", "Port");
        add("screen.mydrugs.machine_transfer.kind", "Kind");
        add("screen.mydrugs.machine_transfer.direction.north", "North");
        add("screen.mydrugs.machine_transfer.direction.south", "South");
        add("screen.mydrugs.machine_transfer.direction.east", "East");
        add("screen.mydrugs.machine_transfer.direction.west", "West");
        add("screen.mydrugs.machine_transfer.direction.up", "Up");
        add("screen.mydrugs.machine_transfer.direction.down", "Down");
        add("screen.mydrugs.machine_transfer.rule.disabled", "Disabled");
        add("screen.mydrugs.machine_transfer.rule.input", "Input");
        add("screen.mydrugs.machine_transfer.rule.output", "Output");
        add("screen.mydrugs.machine_transfer.rule.disabled_short", "Off");
        add("screen.mydrugs.machine_transfer.rule.input_short", "In");
        add("screen.mydrugs.machine_transfer.rule.output_short", "Out");
        add("screen.mydrugs.machine_transfer.open", "Transfer Configuration");
        add("screen.mydrugs.machine_transfer.open_short", "T");
        add("screen.mydrugs.machine_transfer.tooltip", "Transfer Configuration");
        add("screen.mydrugs.machine_transfer.click_to_cycle", "Click to cycle");
        add("screen.mydrugs.machine_transfer.toggle.on", "On");
        add("screen.mydrugs.machine_transfer.toggle.off", "Off");
        add("screen.mydrugs.machine_transfer.input_n", "Input %s");
        add("screen.mydrugs.machine_transfer.output_n", "Output %s");
        add("gui.mydrugs.transfer_side.front", "F");
        add("gui.mydrugs.transfer_side.back", "Ba");
        add("gui.mydrugs.transfer_side.left", "L");
        add("gui.mydrugs.transfer_side.right", "R");
        add("gui.mydrugs.transfer_side.top", "T");
        add("gui.mydrugs.transfer_side.bottom", "Bo");
        add("gui.mydrugs.transfer_world_side.north", "N");
        add("gui.mydrugs.transfer_world_side.south", "S");
        add("gui.mydrugs.transfer_world_side.east", "E");
        add("gui.mydrugs.transfer_world_side.west", "W");
        add("gui.mydrugs.transfer_world_side.up", "U");
        add("gui.mydrugs.transfer_world_side.down", "D");
        add("message.mydrugs.transfer_upgrade.required", "Install a Machine Transfer Upgrade first.");
        add("message.mydrugs.transfer_config.unsupported", "This menu does not support transfer configuration.");
        add("message.mydrugs.transfer_config.open_failed", "Could not open transfer configuration.");
        add("machine_transfer_port.mydrugs.item_input", "Item Input");
        add("machine_transfer_port.mydrugs.item_output", "Item Output");
        add("machine_transfer_port.mydrugs.fuel", "Fuel");
        add("machine_transfer_port.mydrugs.drug_input", "Drug Input");
        add("machine_transfer_port.mydrugs.reagent_input", "Reagent Input");
        add("machine_transfer_port.mydrugs.extract_output", "Extract Output");
        add("machine_transfer_port.mydrugs.residue_output", "Residue Output");
        add("machine_transfer_port.mydrugs.distillate_fuel", "Distillate Fuel");
        add("machine_transfer_port.mydrugs.current_regulator", "Current Regulator");
        add("machine_transfer_port.mydrugs.engine_waste", "Engine Waste");
        add("machine_transfer_port.mydrugs.catalyst", "Catalyst");
        add("machine_transfer_port.mydrugs.fluid_input", "Fluid Input");
        add("machine_transfer_port.mydrugs.fluid_input_a", "Fluid Input A");
        add("machine_transfer_port.mydrugs.fluid_input_b", "Fluid Input B");
        add("machine_transfer_port.mydrugs.fluid_input_c", "Fluid Input C");
        add("machine_transfer_port.mydrugs.fluid_output", "Fluid Output");
        add("machine_transfer_port.mydrugs.gas_input", "Gas Input");
        add("machine_transfer_port.mydrugs.gas_output", "Gas Output");
        add("direction.mydrugs.down", "Down");
        add("direction.mydrugs.up", "Up");
        add("direction.mydrugs.north", "North");
        add("direction.mydrugs.south", "South");
        add("direction.mydrugs.west", "West");
        add("direction.mydrugs.east", "East");
        add("pipe_mode.mydrugs.disabled", "Disabled");
        add("pipe_mode.mydrugs.pipe", "Pipe");
        add("pipe_mode.mydrugs.input", "Input");
        add("pipe_mode.mydrugs.output", "Output");
        add("pipe.mydrugs.kind.item", "Item");
        add("pipe.mydrugs.kind.fluid", "Fluid");
        add("pipe.mydrugs.kind.gas", "Gas");
        add("pipe.mydrugs.filter_mode.allow_list", "Allow List");
        add("pipe.mydrugs.filter_mode.deny_list", "Deny List");
        add("tooltip.mydrugs.psy_receptacle", "A vessel for the first imprint. Used to forge the Psy Anvil.");
        add("tooltip.mydrugs.meth_purity", "Quality: %s");
        add("tooltip.mydrugs.meth_purity.street", "Street-grade");
        add("tooltip.mydrugs.meth_purity.cut", "Cut");
        add("tooltip.mydrugs.meth_purity.pure", "Pure");
        add("tooltip.mydrugs.progression_guide", "A field guide for the full MyDrugs progression path.");
        add("tooltip.mydrugs.adn_scraper", "Scrapes fictional genetic traces from living bodies. Right-click air to sample yourself.");
        add("tooltip.mydrugs.adn_scrap.empty", "No ADN profile detected.");
        add("tooltip.mydrugs.adn_scrap.flavor", "A torn biological signature. Still shaped like its source.");
        add("tooltip.mydrugs.adn_scrap.source", "Source: %s (%s)");
        add("tooltip.mydrugs.adn_scrap.source_player", "Player");
        add("tooltip.mydrugs.adn_scrap.unknown_entity", "Unknown entity: %s");
        add("tooltip.mydrugs.adn_scrap.rarity", "Rarity: %s");
        add("tooltip.mydrugs.adn_scrap.signature", "Signature: %s");
        add("tooltip.mydrugs.adn_scrap.stat", "%s: %s%%");
        add("tooltip.mydrugs.adn_scrap.improbability", "Improbability: %s%%");
        add("tooltip.mydrugs.adn_scrap.source_uuid", "Source UUID: %s");
        add("tooltip.mydrugs.adn_gene.empty", "Empty genetic carrier.");
        add("tooltip.mydrugs.adn_gene.flavor", "A single instruction, waiting to be rewritten.");
        add("tooltip.mydrugs.adn_gene.broken", "The combination failed.");
        add("tooltip.mydrugs.adn_gene.combination_failed", "The combination failed.");
        add("tooltip.mydrugs.adn_gene.restart", "You have to restart over.");
        add("tooltip.mydrugs.adn_gene.sources", "Sources: %s");
        add("tooltip.mydrugs.adn_gene.signature", "Signature: %s");
        add("tooltip.mydrugs.adn_gene.stat", "%s: %s%%");
        add("tooltip.mydrugs.adn_gene.same_source_warning", "Cannot combine with genes from the same source.");
        add("tooltip.mydrugs.adn_gene.source_uuids", "Source UUIDs: %s");
        add("tooltip.mydrugs.mutation_vector.empty", "Empty culture.");
        add("tooltip.mydrugs.mutation_vector.flavor", "A living culture carrying unstable genetic instructions.");
        add("tooltip.mydrugs.mutation_vector.footer", "Must be mixed with blood before injection.");
        add("tooltip.mydrugs.mutagenic_blood_vial.empty", "No mutagenic blood payload.");
        add("tooltip.mydrugs.mutagenic_blood_vial.flavor", "The blood is no longer only blood.");
        add("tooltip.mydrugs.mutagenic_blood_vial.footer", "Requires a sterile syringe.");
        add("tooltip.mydrugs.mutation_payload.sources", "Sources: %s");
        add("tooltip.mydrugs.mutation_payload.signature", "Signature: %s");
        add("tooltip.mydrugs.mutation_payload.stat", "%s: %s%%");
        add("tooltip.mydrugs.mutation_payload.assimilation_difficulty", "Assimilation difficulty: %s%%");
        add("tooltip.mydrugs.mutation_payload.rejection_risk", "Rejection risk: %s%%");
        add("tooltip.mydrugs.mutation_payload.source_uuids", "Source UUIDs: %s");
        add("tooltip.mydrugs.syringe.empty", "Empty.");
        add("tooltip.mydrugs.syringe.filled", "Contains blood.");
        add("tooltip.mydrugs.syringe.blood_amount", "Blood: %s / %s mB");
        add("tooltip.mydrugs.syringe.source_player", "Drawn from %s");
        add("tooltip.mydrugs.syringe.source_entity", "Drawn from %s");
        add("tooltip.mydrugs.syringe.source_id", "Source ID: %s");
        add("tooltip.mydrugs.syringe.sterile", "Sterile");
        add("tooltip.mydrugs.syringe.dirty", "Dirty");
        add("tooltip.mydrugs.syringe.dirty_warning", "Dirty injection can cause infection and destroy mutations.");
        add("tooltip.mydrugs.syringe.mutagenic_blood", "Contains mutagenic blood.");
        add("message.mydrugs.mutation.syringe_dirty", "The syringe is dirty.");
        add("message.mydrugs.mutation.syringe_loaded", "Mutagenic blood loaded into the syringe.");
        add("message.mydrugs.mutation.injection_started", "Something inside you starts changing.");
        add("message.mydrugs.mutation.self_genetics_rejected", "Your body rejects its own genetic echo.");
        add("message.mydrugs.mutation.dirty_injection", "The injection site burns.");
        add("message.mydrugs.mutation.injection_burns", "The injection site burns.");
        add("message.mydrugs.mutation.infection_spreading", "The infection is spreading.");
        add("message.mydrugs.mutation.mutations_collapsing", "Your mutations are collapsing.");
        add("message.mydrugs.mutation.collapse", "Your body collapses under the infection.");
        add("message.mydrugs.mutation.assimilation_complete", "Your body has accepted %s.");
        add("screen.mydrugs.gene_extractor.progress", "Extraction Progress");
        add("screen.mydrugs.gene_extractor.progress_amount", "%s / %s ticks, %s PE/t");
        add("screen.mydrugs.crispr_cas9_combinator.progress", "Combination Progress");
        add("screen.mydrugs.crispr_cas9_combinator.progress_amount", "%s / %s ticks, %s PE/t");
        add("screen.mydrugs.crispr_cas9_combinator.stability", "Combination stability: %s%%");
        add("screen.mydrugs.crispr_cas9_combinator.same_source_short", "Same source blocked");
        add("screen.mydrugs.bacterial_incubator.progress", "Incubation Progress");
        add("screen.mydrugs.bacterial_incubator.progress_amount", "%s / %s ticks, %s PE/t");
        add("screen.mydrugs.hemogenic_infuser.progress", "Infusion Progress");
        add("screen.mydrugs.hemogenic_infuser.progress_amount", "%s / %s ticks, %s PE/t");
        add("screen.mydrugs.psychotrope_distillery.progress", "Distillation Progress");
        add("screen.mydrugs.distillate_engine.radius", "Radius: %s");
        add("screen.mydrugs.distillate_engine.output", "%s PC/t");
        add("screen.mydrugs.distillate_engine.strain", "Strain");
        add("screen.mydrugs.distillate_engine.strain_value", "%s / 100");
        add("screen.mydrugs.psychotrope_resonator.progress", "Ritual Progress");
        add("screen.mydrugs.psychotrope_resonator.button.dream_alignment", "Align");
        add("screen.mydrugs.psychotrope_resonator.button.integration", "Bind");
        add("screen.mydrugs.psychotrope_resonator.button.recovery", "Heal");
        add("screen.mydrugs.psychotrope_resonator.button.dimension", "World");
        add("screen.mydrugs.psychotrope_resonator.tooltip.dream_alignment", "Shape Dream Residue into a coordinate.");
        add("screen.mydrugs.psychotrope_resonator.tooltip.integration", "Integrate the first eligible drug matching the loaded material.");
        add("screen.mydrugs.psychotrope_resonator.tooltip.recovery", "Use Calming Resin with diary and room context to boost active recovery.");
        add("screen.mydrugs.psychotrope_resonator.tooltip.dimension", "Try to open the Inner Dimension.");
        add("screen.mydrugs.psychotrope_resonator.dimension_ready", "Coordinate ready");
        add("screen.mydrugs.psychotrope_resonator.dimension_aligned", "Dream aligned");
        add("screen.mydrugs.psychotrope_resonator.dimension_locked", "Needs integration");
        add("screen.mydrugs.psychotrope_resonator.no_active_drug", "No active drug");
        add("screen.mydrugs.psychotrope_resonator.active_drug", "Drug: %s");
        add("screen.mydrugs.psychotrope_resonator.checklist", "Ritual checklist");
        add("screen.mydrugs.psychotrope_resonator.failure.none", "No failure recorded.");
        add("screen.mydrugs.psychotrope_resonator.candidate", "Target: %s");
        add("screen.mydrugs.psychotrope_resonator.missing.1", "Missing: drug knowledge");
        add("screen.mydrugs.psychotrope_resonator.missing.2", "Missing: peak or clean-dose requirement");
        add("screen.mydrugs.psychotrope_resonator.missing.4", "Missing: current addiction must fall");
        add("screen.mydrugs.psychotrope_resonator.missing.8", "Missing: recovery progress");
        add("screen.mydrugs.psychotrope_resonator.missing.16", "Missing: lifetime dose");
        add("screen.mydrugs.psychotrope_resonator.missing.32", "Missing: matching material");
        add("screen.mydrugs.psychotrope_resonator.missing.64", "Missing: Integration Core");
        add("screen.mydrugs.psychotrope_resonator.missing.128", "Missing: diary context");
        add("screen.mydrugs.psychotrope_resonator.missing.256", "Missing: valid Recovery Room");
        add("screen.mydrugs.psychotrope_resonator.missing.512", "Already integrated");
        add("resonator_state.mydrugs.idle", "Idle");
        add("resonator_state.mydrugs.invalid_structure", "Invalid structure");
        add("resonator_state.mydrugs.awaiting_conditions", "Awaiting conditions");
        add("resonator_state.mydrugs.ready", "Ready");
        add("resonator_state.mydrugs.resonating", "Resonating");
        add("resonator_state.mydrugs.integrating", "Integrating");
        add("resonator_state.mydrugs.dimension_ready", "Dimension ready");
        add("resonator_state.mydrugs.cooldown", "Cooldown");
        add("resonator_state.mydrugs.blocked", "Blocked");
        add("machine_status.mydrugs.blocked", "Blocked");
        add("machine_status.mydrugs.missing_diary_context", "Missing diary context");
        add("machine_status.mydrugs.missing_recovery_context", "Missing recovery context");
        add("machine_status.mydrugs.dimension_unavailable", "Dimension unavailable");
        add("message.mydrugs.resonator.busy", "The Resonator is already holding a ritual.");
        add("message.mydrugs.resonator.requires_lysergic", "The Resonator needs lysergic knowledge first.");
        add("message.mydrugs.resonator.missing_dream_residue", "Dream Residue belongs in the material slot.");
        add("message.mydrugs.resonator.missing_mycelial_insight", "Mycelial Insight belongs in the material slot.");
        add("message.mydrugs.resonator.missing_calming_resin", "Calming Resin belongs in the material slot.");
        add("message.mydrugs.resonator.missing_diary", "A diary with lived context is required.");
        add("message.mydrugs.resonator.missing_recovery_room", "A valid Recovery Room must be nearby.");
        add("message.mydrugs.resonator.no_eligible_drug", "No loaded material matches an eligible integration.");
        add("message.mydrugs.resonator.missing_drug_knowledge", "You do not understand this drug well enough to integrate it.");
        add("message.mydrugs.resonator.missing_integration_core", "An Integration Core is required.");
        add("message.mydrugs.resonator.missing_integration_material", "The material slot does not match the current integration target.");
        add("message.mydrugs.resonator.peak_too_low", "The peak or exposure requirement is not met yet.");
        add("message.mydrugs.resonator.addiction_too_high", "Current addiction is still too high.");
        add("message.mydrugs.resonator.recovery_incomplete", "Recovery progress is not complete yet.");
        add("message.mydrugs.resonator.lifetime_dose_low", "Lifetime dose is too low for this integration.");
        add("message.mydrugs.resonator.clean_streak_low", "Clean psychedelic dose streak is incomplete.");
        add("message.mydrugs.resonator.already_integrated", "That trait is already integrated.");
        add("message.mydrugs.resonator.dream_already_aligned", "Your Dream Alignment is already complete.");
        add("message.mydrugs.resonator.integration_lost", "The integration conditions slipped out of alignment.");
        add("message.mydrugs.integration_core.awarded", "Coffee crossed its integration peak. An Integration Core has found you.");
        add("message.mydrugs.inner_dimension.requires_integration", "The inner world will not open before integration.");
        add("message.mydrugs.inner_dimension.requires_dream_alignment", "The inner world needs personal Dream Alignment.");
        add("message.mydrugs.inner_dimension.unavailable", "The inner world cannot be reached from here.");
        add("message.mydrugs.psy_mixer.recovery.integration_core_locked", "The seed ritual stays quiet until your first Integration Core has found you.");
        add("tooltip.mydrugs.integration_core.1", "Received when coffee reaches its first integration peak.");
        add("tooltip.mydrugs.integration_core.2", "Binds a recovered experience into a permanent integrated trait.");
        add("tooltip.mydrugs.integration_core.3", "Use it in the Psychotrope Resonator with diary, room, and material.");
        add("tooltip.mydrugs.integration_core.4", "More can be made later through the Psy Mixer seed ritual.");
        add("integration.mydrugs.trait.clear_focus", "Clear Focus");
        add("integration.mydrugs.trait.clear_focus.reward", "Manual work speed +20%, focus +10%.");
        add("integration.mydrugs.trait.steady_hands", "Steady Hands");
        add("integration.mydrugs.trait.steady_hands.reward", "Precision +16%, mining speed +8%, tremor reduction +12%.");
        add("integration.mydrugs.trait.even_keel", "Even Keel");
        add("integration.mydrugs.trait.even_keel.reward", "Stress resistance +22%, bad-trip resistance +8%.");
        add("integration.mydrugs.trait.fine_motor", "Fine Motor");
        add("integration.mydrugs.trait.fine_motor.reward", "Precision +18%, ritual stability +12%.");
        add("integration.mydrugs.trait.hardened", "Hardened");
        add("integration.mydrugs.trait.hardened.reward", "Damage resistance +14%, stress resistance +8%.");
        add("integration.mydrugs.trait.quickstep", "Quickstep");
        add("integration.mydrugs.trait.quickstep.reward", "Movement speed +12%, manual work speed +12%.");
        add("integration.mydrugs.trait.richer_seams", "Richer Seams");
        add("integration.mydrugs.trait.richer_seams.reward", "Ore fortune +12%, ore aura +15%, ritual focus +10%.");
        add("integration.mydrugs.trait.overdrive_memory", "Overdrive Memory");
        add("integration.mydrugs.trait.overdrive_memory.reward", "Mining speed +20%, manual work speed +18%.");
        add("integration.mydrugs.trait.structural_sense", "Structural Sense");
        add("integration.mydrugs.trait.structural_sense.reward", "Multiblock vision, plus low-light vision +35%.");
        add("screen.mydrugs.diary.integration.title", "%s Integration");
        add("screen.mydrugs.diary.integration.drug", "Drug: %s");
        add("screen.mydrugs.diary.integration.reward", "Trait reward");
        add("screen.mydrugs.diary.integration.checklist", "Checklist");
        add("screen.mydrugs.diary.integration.knowledge", "Knowledge unlocked");
        add("screen.mydrugs.diary.integration.clean_doses", "Clean doses: %s / %s");
        add("screen.mydrugs.diary.integration.peak", "Peak/exposure: %s / %s");
        add("screen.mydrugs.diary.integration.current_addiction", "Current addiction: %s / %s max");
        add("screen.mydrugs.diary.integration.lifetime", "Lifetime dose: %s / %s");
        add("screen.mydrugs.diary.integration.recovery", "Recovery progress: %s");
        add("screen.mydrugs.diary.integration.diary", "Diary context present");
        add("screen.mydrugs.diary.integration.room", "Valid Recovery Room nearby");
        add("screen.mydrugs.diary.integration.material", "Material in inventory: %s");
        add("screen.mydrugs.diary.integration.core", "Integration Core in inventory");
        add("screen.mydrugs.diary.integration.not_integrated", "Trait not already integrated");
        add("screen.mydrugs.diary.integration.integrated", "Already integrated");
        add("diary.mydrugs.integration.roleplay.coffee", "The hand learned speed before the mind learned rest.");
        add("diary.mydrugs.integration.roleplay.tobacco", "Steadiness became a ritual before it became a choice.");
        add("diary.mydrugs.integration.roleplay.weed", "Calm is not absence. It is something I can build.");
        add("diary.mydrugs.integration.roleplay.hash", "Still hands can shape small things without needing hunger.");
        add("diary.mydrugs.integration.roleplay.alcohol", "Borrowed courage left a bruise. Kept courage stands cleaner.");
        add("diary.mydrugs.integration.roleplay.cocaine", "Speed taught the body a route. Recovery decides where it leads.");
        add("diary.mydrugs.integration.roleplay.lsd", "Five doors opened. None swallowed me.");
        add("diary.mydrugs.integration.roleplay.meth", "The overdrive became memory instead of command.");
        add("diary.mydrugs.integration.roleplay.mushrooms", "The structure was never outside me alone.");
        add("screen.mydrugs.ui.inventory", "Inventory");
        add("screen.mydrugs.ui.psy_current", "Psy Current");
        add("screen.mydrugs.ui.psy_current_value", "%s / %s PC");
        add("screen.mydrugs.ui.amount", "%s / %s");
        add("screen.mydrugs.ui.amount_unit", "%s / %s %s");
        add("screen.mydrugs.ui.fuel_burn", "Fuel burn");
        add("screen.mydrugs.jei.residue", "Residue");
        add("screen.mydrugs.jei.residue_every", " | Residue: every %s crafts");
        add("screen.mydrugs.jei.residue_every_tooltip", "Generated every %s completed crafts.");
        add("machine_transfer_port.mydrugs.adn_input", "ADN Input");
        add("machine_transfer_port.mydrugs.gene_output_a", "Gene Output A");
        add("machine_transfer_port.mydrugs.gene_output_b", "Gene Output B");
        add("machine_transfer_port.mydrugs.gene_output_c", "Gene Output C");
        add("machine_transfer_port.mydrugs.gene_input_a", "Gene Input A");
        add("machine_transfer_port.mydrugs.gene_input_b", "Gene Input B");
        add("machine_transfer_port.mydrugs.gene_output", "Gene Output");
        add("machine_transfer_port.mydrugs.gene_input", "Gene Input");
        add("machine_transfer_port.mydrugs.nutrient_input", "Nutrient Input");
        add("machine_transfer_port.mydrugs.vector_output", "Vector Output");
        add("machine_transfer_port.mydrugs.vector_input", "Vector Input");
        add("machine_transfer_port.mydrugs.blood_input", "Blood Input");
        add("machine_transfer_port.mydrugs.mutagenic_blood_output", "Mutagenic Blood Output");
        add("message.mydrugs.adn_scraper.too_weak", "You are too weak to extract your own ADN.");
        add("message.mydrugs.adn_scraper.invalid_target", "No usable ADN traces found.");
        add("message.mydrugs.crispr.same_source", "Genes from the same source cannot be combined.");
        add("mutation.mydrugs.rarity.common", "Common");
        add("mutation.mydrugs.rarity.uncommon", "Uncommon");
        add("mutation.mydrugs.rarity.rare", "Rare");
        add("mutation.mydrugs.rarity.dangerous", "Dangerous");
        add("mutation.mydrugs.rarity.mythic", "Mythic");
        add("mutation.mydrugs.stat.visual_accuracy", "Visual Accuracy");
        add("mutation.mydrugs.stat.visual_accuracy.desc", "Reduces harmful visual distortion without weakening gamma boost.");
        add("mutation.mydrugs.stat.health_stability", "Health Stability");
        add("mutation.mydrugs.stat.health_stability.desc", "Stabilizes damage caused by internal drug stress.");
        add("mutation.mydrugs.stat.addiction_resistance", "Addiction Resistance");
        add("mutation.mydrugs.stat.addiction_resistance.desc", "Reduces future addiction pressure.");
        add("mutation.mydrugs.stat.mental_strength", "Mental Strength");
        add("mutation.mydrugs.stat.mental_strength.desc", "Helps resist mental symptoms and bad-trip pressure.");
        add("mutation.mydrugs.stat.pleasure_sensitivity", "Pleasure Sensitivity");
        add("mutation.mydrugs.stat.pleasure_sensitivity.desc", "Improves positive drug effects but may increase craving pressure.");
        add("mutation.mydrugs.stat.withdrawal_resilience", "Withdrawal Resilience");
        add("mutation.mydrugs.stat.withdrawal_resilience.desc", "Helps resist physical withdrawal symptoms.");
        add("mutation.mydrugs.stat.metabolic_control", "Metabolic Control");
        add("mutation.mydrugs.stat.metabolic_control.desc", "Helps the body process dangerous dose states.");
        add("mutation.mydrugs.stat.ritual_neural_sync", "Ritual Neural Sync");
        add("mutation.mydrugs.stat.ritual_neural_sync.desc", "Improves compatibility with future Psy Mixer systems.");
        add("mutation.mydrugs.stat.infection_resistance", "Infection Resistance");
        add("mutation.mydrugs.stat.infection_resistance.desc", "Slows future infection progression.");
        add("mutation.mydrugs.stat.genetic_stability", "Genetic Stability");
        add("mutation.mydrugs.stat.genetic_stability.desc", "Reduces future mutation instability.");
        add("mutation.mydrugs.stat.unknown", "Unknown stat: %s");
        add("tooltip.mydrugs.mycelial_resonator", "It hums toward places where the ground dreams.");
        add("message.mydrugs.mycelial_resonator.use", "The hum points toward damp, strange ground. The research is still incomplete.");
        add("knowledge.mydrugs.caffeine", "Caffeine Knowledge");
        add("knowledge.mydrugs.nicotinic", "Nicotinic Knowledge");
        add("knowledge.mydrugs.cannabinoid", "Cannabinoid Knowledge");
        add("knowledge.mydrugs.fermented", "Fermented Knowledge");
        add("knowledge.mydrugs.stimulant", "Stimulant Knowledge");
        add("knowledge.mydrugs.lysergic", "Lysergic Knowledge");
        add("knowledge.mydrugs.overclocked", "Overclocked Knowledge");
        add("knowledge.mydrugs.mycelial", "Mycelial Knowledge");
        add("message.mydrugs.knowledge.caffeine", "Your hands will not stop moving. The Psy Receptacle wakes with them.");
        add("message.mydrugs.knowledge.nicotinic", "Your lungs have signed the tutorial waiver.");
        add("message.mydrugs.knowledge.cannabinoid", "Your thoughts are buffering... and copper suddenly feels negotiable.");
        add("message.mydrugs.knowledge.fermented", "You have discovered structural confidence. Heavy iron unlocked.");
        add("tooltip.mydrugs.insulated_wire.fermented_reward.1", "Gosh, I drank too much. I made a mess with my copper and ended up with this.");
        add("tooltip.mydrugs.insulated_wire.fermented_reward.2", "What is it even for? I tried making it again while drinking, but it led to nothing.");
        add("tooltip.mydrugs.insulated_wire.fermented_reward.3", "Maybe the first time only worked because of that overstimulation.");
        add("tooltip.mydrugs.insulated_wire.fermented_reward.4", "Stimulation might be the key. I should find out quickly.");
        add("message.mydrugs.knowledge.stimulant", "Your neurons formed a committee and immediately overclocked it.");
        add("message.mydrugs.knowledge.lysergic", "The walls submitted a circuit diagram. It was correct.");
        add("message.mydrugs.knowledge.overclocked", "The lab heard boss music and started working faster.");
        add("message.mydrugs.knowledge.mycelial", "You found the valley. The valley found you back.");
        add("message.mydrugs.bad_trip.start.1", "Something in your mind turns against you.");
        add("message.mydrugs.bad_trip.start.2", "Your thoughts begin to move without you.");
        add("message.mydrugs.bad_trip.start.3", "The trip has turned.");
        add("message.mydrugs.bad_trip.start.4", "You are no longer alone in your own head.");
        add("message.mydrugs.bad_trip.end", "Your thoughts begin to settle.");
        add("message.mydrugs.bad_trip.shelter", "The room steadies you.");
        add("message.mydrugs.bad_trip.shelter_strong", "The walls hold.");
        add("message.mydrugs.bad_trip.shelter.strong", "The walls hold.");
        add("recovery.mydrugs.room.none", "No Room");
        add("recovery.mydrugs.room.fragile", "Fragile Room");
        add("recovery.mydrugs.room.resting", "Resting Room");
        add("recovery.mydrugs.room.safe", "Safe Room");
        add("recovery.mydrugs.room.sanctuary", "Sanctuary");
        add("recovery.mydrugs.room.score", "Recovery Room: %s - Comfort %s%%");
        add("recovery.mydrugs.room.overlay", "%s - Comfort %s%%");
        add("recovery.mydrugs.room.overlay_highlight", "%s - Comfort %s%% (room highlighted)");
        add("recovery.mydrugs.room.good", "Good: %s");
        add("recovery.mydrugs.room.modules", "Sanctuary modules: %s");
        add("recovery.mydrugs.room.module_suggestions", "Sanctuary ideas: %s");
        add("recovery.mydrugs.room.improve", "Improve: %s");
        add("recovery.mydrugs.room.invalid", "The anchor cannot find a room yet.");
        add("recovery.mydrugs.room.needs_door", "The room needs a way to close.");
        add("recovery.mydrugs.room.needs_bed", "Add a bed.");
        add("recovery.mydrugs.room.soft_lighting", "Add softer lighting.");
        add("recovery.mydrugs.room.too_large", "Room slightly too large.");
        add("recovery.mydrugs.room.too_small", "Room too small.");
        add("recovery.mydrugs.room.too_many_books", "Bookshelves are helpful, but too many make the room feel crowded.");
        add("recovery.mydrugs.room.music", "Add an activated jukebox or recovery music.");
        add("recovery.mydrugs.room.sanctuary_memory", "This room learned how to hold me.");
        add("recovery.mydrugs.room.too_exposed", "Too exposed.");
        add("recovery.mydrugs.room.too_many_doors", "Too many open exits.");
        add("recovery.mydrugs.room.needs_carpets", "Add carpets.");
        add("recovery.mydrugs.room.needs_flowers", "Add flowers.");
        add("recovery.mydrugs.room.too_dangerous", "Remove dangerous blocks or threats.");
        add("recovery.mydrugs.room.polish_size", "Tune the room size toward a small bedroom: not cramped, not open.");
        add("recovery.mydrugs.room.polish_enclosure", "Use calmer walls or glass, and close off any exposed edges.");
        add("recovery.mydrugs.room.polish_lighting", "Balance the light with lanterns, candles, or glow blocks instead of torch spam.");
        add("recovery.mydrugs.room.polish_carpets", "Use a moderate amount of carpet or wool floor comfort.");
        add("recovery.mydrugs.room.polish_plants", "Add a few more plants or flower pots.");
        add("recovery.mydrugs.room.polish_books", "Add one to six bookshelves or a lectern, but keep it uncluttered.");
        add("recovery.mydrugs.room.polish_music", "Keep an active jukebox or recovery music in the room.");
        add("recovery.mydrugs.room.polish_complete", "This room is already a strong sanctuary; keep it calm and uncluttered.");
        add("recovery.mydrugs.component.size", "right size");
        add("recovery.mydrugs.component.enclosure", "enclosure");
        add("recovery.mydrugs.component.door", "door");
        add("recovery.mydrugs.component.bed", "bed");
        add("recovery.mydrugs.component.soft_lighting", "soft lighting");
        add("recovery.mydrugs.component.carpets", "carpets");
        add("recovery.mydrugs.component.flowers", "flowers");
        add("recovery.mydrugs.component.books", "books");
        add("recovery.mydrugs.component.music", "music");
        add("recovery.mydrugs.room.component.bed", "bed");
        add("recovery.mydrugs.room.component.door", "door");
        add("recovery.mydrugs.room.component.soft_lighting", "soft lighting");
        add("recovery.mydrugs.room.component.carpets", "carpets");
        add("recovery.mydrugs.room.component.flowers", "flowers");
        add("recovery.mydrugs.room.component.books", "books");
        add("recovery.mydrugs.room.component.music", "music");
        add("recovery.mydrugs.room.component.enclosure", "enclosure");
        add("recovery.mydrugs.room.module.rest_module", "resting place");
        add("recovery.mydrugs.room.module.diary_desk", "diary desk");
        add("recovery.mydrugs.room.module.music_corner", "music corner");
        add("recovery.mydrugs.room.module.plant_breathing_corner", "plant corner");
        add("recovery.mydrugs.room.module.tea_kitchen", "tea kitchen");
        add("recovery.mydrugs.room.module.memory_wall", "memory wall");
        add("recovery.mydrugs.room.module.integration_alcove", "integration alcove");
        add("recovery.mydrugs.room.module_suggestion.rest_module", "A bed with calm light makes rest more reliable.");
        add("recovery.mydrugs.room.module_suggestion.diary_desk", "A lectern, books, and a seat would make reflection clearer.");
        add("recovery.mydrugs.room.module_suggestion.music_corner", "Music may help the room hold during crisis.");
        add("recovery.mydrugs.room.module_suggestion.plant_breathing_corner", "Plants can make the room easier to breathe in.");
        add("recovery.mydrugs.room.module_suggestion.tea_kitchen", "A small tea setup can turn recovery into preparation.");
        add("recovery.mydrugs.room.module_suggestion.memory_wall", "Displayed memories can help the room remember what you survived.");
        add("recovery.mydrugs.room.module_suggestion.integration_alcove", "An integration alcove will matter when recovery turns into integration.");
        add("screen.mydrugs.music.title", "Headphones");
        add("screen.mydrugs.music.now_playing", "Now Playing");
        add("screen.mydrugs.music.liked", "Liked");
        add("screen.mydrugs.music.add", "Add");
        add("screen.mydrugs.music.import_file", "Import File");
        add("screen.mydrugs.music.import_folder", "Import Folder");
        add("screen.mydrugs.music.add_direct_url", "Add Direct URL");
        add("screen.mydrugs.music.add_bookmark", "Add Bookmark");
        add("screen.mydrugs.music.pause", "Pause");
        add("screen.mydrugs.music.play", "Play");
        add("screen.mydrugs.music.next", "Next");
        add("screen.mydrugs.music.previous", "Previous");
        add("screen.mydrugs.music.shuffle", "Shuffle");
        add("screen.mydrugs.music.repeat", "Repeat");
        add("screen.mydrugs.music.no_track_selected", "No track selected.");
        add("screen.mydrugs.disc_scriber.title", "Disc Scriber");
        add("screen.mydrugs.disc_scriber.scribe", "Scribe Disc");
        add("screen.mydrugs.disc_scriber.selected", "Selected:");
        add("screen.mydrugs.disc_scriber.has_blank_disc", "Blank disc ready.");
        add("screen.mydrugs.disc_scriber.no_blank_disc", "No blank music disc.");
        add("screen.mydrugs.disc_scriber.sent", "Scribing request sent.");
        add("screen.mydrugs.music.unsupported", "Unsupported format; convert to .ogg.");
        add("screen.mydrugs.music.missing_file", "Missing file.");
        add("screen.mydrugs.music.bookmark_only", "Music-service links are saved as bookmarks only. Import a local file you have rights to in order to play it in-game.");
        add("screen.mydrugs.music.importing", "Importing...");
        add("screen.mydrugs.music.downloading", "Downloading...");
        add("screen.mydrugs.music.done", "Done");
        add("screen.mydrugs.music.failed", "Failed: %s");
        add("screen.mydrugs.music.duplicate", "Track already imported.");
        add("screen.mydrugs.music.empty", "No track selected");
        add("screen.mydrugs.music.empty_help", "Import local .ogg files or save links as bookmarks.");
        add("screen.mydrugs.music.search", "Search");
        add("screen.mydrugs.music.open_folder", "Open Folder");
        add("screen.mydrugs.music.volume", "Volume %s%%");
        add("screen.mydrugs.music.import_title", "Add Music");
        add("screen.mydrugs.music.path_or_url", "Path or URL");
        add("message.mydrugs.music.missing_local_track", "Missing local track: %s");
        add("message.mydrugs.music.no_blank_disc", "You need a blank music disc.");
        add("message.mydrugs.music.no_track_selected", "Choose a track first.");
        add("message.mydrugs.music.scribe_too_far", "You are too far from the Disc Scriber.");
        add("message.mydrugs.music.disc_created", "Created personal music disc: %s");
        add("message.mydrugs.music.jukebox_started", "Recovery Jukebox started.");
        add("message.mydrugs.music.jukebox_stopped", "Recovery Jukebox stopped.");
        add("tooltip.mydrugs.personal_disc.title", "Title: %s");
        add("tooltip.mydrugs.personal_disc.artist", "Artist: %s");
        add("tooltip.mydrugs.personal_disc.duration", "Duration: %s");
        add("tooltip.mydrugs.personal_disc.track_id", "Track ID: %s");
        add("tooltip.mydrugs.personal_disc.unknown_artist", "Unknown Artist");
        add("tooltip.mydrugs.personal_disc.requires_local_track", "Requires local track in your MyDrugs music library.");
        add("subtitles.mydrugs.write", "Diary scratches");
        add("psyche.mydrugs.node.first_sanctuary.title", "First Sanctuary");
        add("psyche.mydrugs.node.first_sanctuary.caption", "This room learned how to hold me.");
        add("message.mydrugs.knowledge.blocked.generic", "Your mind has no receptacle for this yet. Start smaller.");
        add("message.mydrugs.knowledge.blocked.mushroom", "The valley speaks, but you do not yet know the language.");
        add("message.mydrugs.clay_vat.needs_heat", "The clay vat needs heat below it.");
        add("message.mydrugs.clay_vat.not_enough_water", "Add at least 250 mB water first.");
        add("message.mydrugs.clay_vat.water_batch_size", "Use water in 250 mB batches.");
        add("message.mydrugs.clay_vat.not_enough_powder", "Need %s coffee powder for this batch.");
        add("message.mydrugs.psy_anvil.no_recipe", "The Psy Anvil squints at those items and refuses to improvise.");
        add("message.mydrugs.psy_anvil.locked", "Knowledge missing: %s");
        add("screen.mydrugs.psy_anvil.unknown", "Unknown Knowledge");
        add("screen.mydrugs.bonus.coffee_focus", "Coffee Focus: +%s%% work speed");
        add("screen.mydrugs.bonus.stimulant_rush", "Stimulant Rush: +%s%% work speed");
        add("screen.mydrugs.bonus.adrenaline_hands", "Overclocked Hands: +%s%% work speed");
        add("screen.mydrugs.bonus.tobacco_precision", "Tobacco Precision: +%s%% work speed");
        add("screen.mydrugs.bonus.ritual_focus", "Ritual Focus: golden zone widened");
        add("screen.mydrugs.bonus.cannabis_calm", "Cannabis Calm: ritual mistakes are easier to recover from");
        add("screen.mydrugs.bonus.psychedelic_insight", "Psychedelic Insight: full ritual window");
        add("screen.mydrugs.psy_mixer.formula", "Formula: %s");
        add("screen.mydrugs.psy_mixer.formula_derived", "Base + modifier");
        add("screen.mydrugs.psy_mixer.quality", "Quality: %s");
        add("screen.mydrugs.psy_mixer.quality.crude", "Crude");
        add("screen.mydrugs.psy_mixer.quality.base", "Base");
        add("screen.mydrugs.psy_mixer.quality.perfect", "Perfect");
        add("screen.mydrugs.psy_mixer.quality.masterwork", "Masterwork");
        add("screen.mydrugs.psy_mixer.one_voice", "The Mixer accepts only one voice.");
        add("screen.mydrugs.psy_mixer.ritual_required", "Ritual required.");
        add("screen.mydrugs.psy_mixer.no_ritual_required", "No ritual required.");
        add("screen.mydrugs.psy_mixer.begin_ritual", "Begin Ritual");
        add("screen.mydrugs.psy_mixer.current_action", "Step %s / %s");
        add("screen.mydrugs.psy_mixer.quality_preview", "Quality: %s");
        add("screen.mydrugs.psy_mixer.mistakes", "Mistakes: %s/%s");
        add("screen.mydrugs.psy_mixer.last_judgement", "Last: %s");
        add("ritual.mydrugs.action.none.prompt", "");
        add("ritual.mydrugs.action.none.hint", "");
        add("ritual.mydrugs.action.sneak.prompt", "Lower your body.");
        add("ritual.mydrugs.action.sneak.hint", "Sneak.");
        add("ritual.mydrugs.action.jump.prompt", "Break the line.");
        add("ritual.mydrugs.action.jump.hint", "Jump.");
        add("ritual.mydrugs.action.right_click_air.prompt", "Reach into nothing.");
        add("ritual.mydrugs.action.right_click_air.hint", "Right-click air.");
        add("ritual.mydrugs.action.walk_ring.prompt", "Walk the ring.");
        add("ritual.mydrugs.action.walk_ring.hint", "Circle the machine.");
        add("ritual.mydrugs.action.look_at_core.prompt", "Look inside the machine.");
        add("ritual.mydrugs.action.look_at_core.hint", "Look at the core.");
        add("ritual.mydrugs.action.timing_ring.prompt", "Prove your timing.");
        add("ritual.mydrugs.action.timing_ring.hint", "Press Space when the ring reaches gold.");
        add("ritual.mydrugs.action.stand_still.prompt", "Do not interrupt the thought.");
        add("ritual.mydrugs.action.stand_still.hint", "Stand still.");
        add("ritual.mydrugs.action.hold_item.prompt", "Become the vessel.");
        add("ritual.mydrugs.action.hold_item.hint", "Hold the required item.");
        add("ritual.mydrugs.action.reopen_gui.prompt", "Look inside the machine.");
        add("ritual.mydrugs.action.reopen_gui.hint", "Reopen the Psy Mixer.");
        add("ritual.mydrugs.judgement.miss", "Miss");
        add("ritual.mydrugs.judgement.near", "Near");
        add("ritual.mydrugs.judgement.good", "Good");
        add("ritual.mydrugs.judgement.great", "Great");
        add("ritual.mydrugs.judgement.perfect", "Perfect");
        add("tooltip.mydrugs.mixed_drug.quality", "Quality: %s");
        add("tooltip.mydrugs.mixed_drug.quality_effects", "Positive effects: %s%%, Negative effects: %s%%");
        add("item.mydrugs.mixed_drug.name.crude", "Crude %s");
        add("item.mydrugs.mixed_drug.name.perfect", "Perfect %s");
        add("item.mydrugs.mixed_drug.name.masterwork", "Masterwork %s");
        add("screen.mydrugs.formula.quality", "Quality: %s");
        add("key.categories.mydrugs", "MyDrugs");
        add("key.mydrugs.stimulant_dash", "Stimulant Dash");
        add("screen.mydrugs.jei.required_drug_category", "Needs active category: %s");
        add("screen.mydrugs.jei.required_active_effect", "Needs active effect: %s");
        add("screen.mydrugs.jei.required_bad_trip", "Requires a bad trip state");
        add("screen.mydrugs.jei.machine_speed_modifier", "Ritual speed: +%s%%");
        add("screen.mydrugs.jei.ritual_actions", "Actions: %s");
        add("screen.mydrugs.jei.quality_tiers", "Quality tiers: Crude, Base, Perfect, Masterwork");
        add("screen.mydrugs.jei.psy_mixer_deterministic", "Same inputs make the same formula; ritual performance sets quality.");
        add("screen.mydrugs.jei.optional_psy_mixer_items", "Optional items: catalyst +score, stabilizer +time, vessel +forgiveness.");

        // Fluids + fluid buckets
        for (FluidEntry entry : ModFluids.ALL.values()) {
            String pretty = pretty(entry.name());

            // If you keep the default FluidType description id, the registry name is <name>_type
            add("fluid_type." + MyDrugs.MODID + "." + entry.name() + "_type", pretty);

            // Optional fallback if you later set a custom description id without "_type"
            add("fluid_type." + MyDrugs.MODID + "." + entry.name(), pretty);

            add("item." + MyDrugs.MODID + "." + entry.name() + "_bucket", pretty + " Bucket");
            add("block." + MyDrugs.MODID + "." + entry.name(), pretty);
        }
    }
}
