package org.mydrugs.mydrugs.compat;

import mezz.jei.api.gui.builder.IRecipeLayoutBuilder;
import mezz.jei.api.gui.ingredient.IRecipeSlotsView;
import mezz.jei.api.helpers.IGuiHelper;
import mezz.jei.api.recipe.IFocusGroup;
import mezz.jei.api.recipe.RecipeIngredientRole;
import mezz.jei.api.recipe.RecipeType;
import net.minecraft.client.gui.GuiGraphics;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import org.mydrugs.mydrugs.MyDrugs;
import org.mydrugs.mydrugs.blocks.ModBlocks;
import org.mydrugs.mydrugs.blocks.entity.BiochemicalReactorBlockEntity;
import org.mydrugs.mydrugs.menu.client.util.MachineGuiRenderer;
import org.mydrugs.mydrugs.menu.layout.BiochemicalReactorLayout;
import org.mydrugs.mydrugs.recipes.biochemical_reactor.BiochemicalReactorRecipe;

import java.util.List;

final class BiochemicalReactorRecipeCategory extends AbstractNiceRecipeCategory<BiochemicalReactorRecipe> {
    static final RecipeType<BiochemicalReactorRecipe> TYPE =
            new RecipeType<>(ResourceLocation.fromNamespaceAndPath(MyDrugs.MODID, "biochemical_reactor"), BiochemicalReactorRecipe.class);

    BiochemicalReactorRecipeCategory(IGuiHelper helper) {
        super(
                helper,
                TYPE,
                Component.translatable("block.mydrugs.biochemical_reactor"),
                JeiCompatUtil.iconFromField(helper, ModBlocks.class, "BIOCHEMICAL_REACTOR"),
                BiochemicalReactorLayout.GUI_WIDTH,
                MachineGuiRenderer.biochemicalReactorHeight(false)
        );
    }

    @Override
    public void setRecipe(IRecipeLayoutBuilder builder, BiochemicalReactorRecipe recipe, IFocusGroup focuses) {
        addItemIngredient(builder, RecipeIngredientRole.INPUT, BiochemicalReactorLayout.ERGOT_SLOT_X, BiochemicalReactorLayout.ERGOT_SLOT_Y, JeiCompatUtil.ingredientOf(recipe.ergot()));
        addItemIngredient(builder, RecipeIngredientRole.INPUT, BiochemicalReactorLayout.TRYPTOPHAN_SLOT_X, BiochemicalReactorLayout.TRYPTOPHAN_SLOT_Y, JeiCompatUtil.ingredientOf(recipe.tryptophan()));

        addFluid(
                builder,
                RecipeIngredientRole.OUTPUT,
                BiochemicalReactorLayout.OUTPUT_SLOT_X,
                BiochemicalReactorLayout.OUTPUT_SLOT_Y,
                JeiCompatUtil.idOf(recipe.fluidOutput(), "fluid", "fluidId"),
                JeiCompatUtil.intOf(recipe.fluidOutput(), "amount")
        );
    }

    @Override
    public void draw(BiochemicalReactorRecipe recipe, IRecipeSlotsView slots, GuiGraphics g, double mouseX, double mouseY) {
        MachineGuiRenderer.drawBiochemicalReactor(
                this,
                g,
                MachineGuiRenderer.BiochemicalReactorState.recipe(
                        JeiCompatUtil.idOf(recipe.fluidOutput(), "fluid", "fluidId"),
                        JeiCompatUtil.intOf(recipe.fluidOutput(), "amount"),
                        BiochemicalReactorBlockEntity.OUTPUT_TANK_CAPACITY,
                        JeiCompatUtil.countOf(recipe.ergot()),
                        JeiCompatUtil.countOf(recipe.tryptophan())
                ),
                false
        );
        MachineGuiRenderer.drawBiochemicalReactorRecipeLabels(
                this,
                g,
                getTitle(),
                "Processing",
                "Heat >= " + recipe.minimumHeat() + "  |  Time: " + recipe.processingTime() + "t"
        );
    }

    @Override
    public List<Component> getTooltipStrings(BiochemicalReactorRecipe recipe, IRecipeSlotsView slots, double mouseX, double mouseY) {
        if (isHoveringBox(BiochemicalReactorLayout.PROGRESS_X, BiochemicalReactorLayout.PROGRESS_Y, BiochemicalReactorLayout.PROGRESS_W, BiochemicalReactorLayout.PROGRESS_H, mouseX, mouseY)) {
            return amountTooltip("Progress", 0, recipe.processingTime(), "units");
        } else if (isHoveringBox(BiochemicalReactorLayout.HEAT_BAR_X, BiochemicalReactorLayout.HEAT_BAR_Y, BiochemicalReactorLayout.HEAT_BAR_W, BiochemicalReactorLayout.HEAT_BAR_H, mouseX, mouseY)) {
            return tooltip(
                    Component.literal("Heat"),
                    Component.literal(recipe.minimumHeat() + " minimum"),
                    Component.literal("Raises processing speed")
            );
        } else if (isHoveringBox(BiochemicalReactorLayout.MANUAL_BAR_X, BiochemicalReactorLayout.MANUAL_BAR_Y, BiochemicalReactorLayout.MANUAL_BAR_W, BiochemicalReactorLayout.MANUAL_BAR_H, mouseX, mouseY)) {
            return tooltip("Manual Energy", "0 / 100", "Generated by player interaction");
        } else if (isHoveringBox(BiochemicalReactorLayout.OUTPUT_TANK_X, BiochemicalReactorLayout.OUTPUT_TANK_Y, BiochemicalReactorLayout.TANK_W, BiochemicalReactorLayout.TANK_H, mouseX, mouseY)) {
            return fluidTankTooltip(
                    "Output Tank",
                    JeiCompatUtil.idOf(recipe.fluidOutput(), "fluid", "fluidId"),
                    JeiCompatUtil.intOf(recipe.fluidOutput(), "amount"),
                    BiochemicalReactorBlockEntity.OUTPUT_TANK_CAPACITY
            );
        } else if (isHoveringBox(BiochemicalReactorLayout.MANUAL_BUTTON_X, BiochemicalReactorLayout.MANUAL_BUTTON_Y, BiochemicalReactorLayout.MANUAL_BUTTON_W, BiochemicalReactorLayout.MANUAL_BUTTON_H, mouseX, mouseY)) {
            return tooltip("Manual Boost", "Click to add manual energy");
        } else if (isHoveringBox(BiochemicalReactorLayout.ERGOT_SLOT_X, BiochemicalReactorLayout.ERGOT_SLOT_Y, 18, 18, mouseX, mouseY)) {
            return tooltip("Ergot", "More Ergot in this slot increases speed");
        } else if (isHoveringBox(BiochemicalReactorLayout.TRYPTOPHAN_SLOT_X, BiochemicalReactorLayout.TRYPTOPHAN_SLOT_Y, 18, 18, mouseX, mouseY)) {
            return tooltip("Tryptophan");
        } else if (isHoveringBox(BiochemicalReactorLayout.CHARCOAL_SLOT_X, BiochemicalReactorLayout.CHARCOAL_SLOT_Y, 18, 18, mouseX, mouseY)) {
            return tooltip("Charcoal", "Adds heat to the reactor");
        } else if (isHoveringBox(BiochemicalReactorLayout.OUTPUT_SLOT_X, BiochemicalReactorLayout.OUTPUT_SLOT_Y, 18, 18, mouseX, mouseY)) {
            return tooltip("Output Container");
        }
        return List.of();
    }
}
